import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CursorFollow from "@/components/common/CursorFollow";
import MenuBar from "@/components/common/MenuBar";
import NavBar from "@/components/common/NavBar";
import { AppProvider } from "@/components/common/AppContext";
import CanvasSection from "@/components/common/CanvasSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        

        <AppProvider>
        <CursorFollow />
        <MenuBar/>
        <NavBar/>
        {children}
        <CanvasSection />
        </AppProvider>
      </body>
    </html>
  );
}
